### ISSUE TITLE
dependency on multiple days of task

### ISSUE THREAD

**Issue by cgelman** [mistercrunch/Airflow#212]
I'd like to setup a weekly hive task that depends on 7 days worth of hive data from another task.  In looking at setting up upstream dependencies - it looks like:
1) You can set up same day dependencies on a task via the t2.set_upstream(t1), but you can't specify a date here.
2) You can set up a HivePartitionSensor, and specify a certain relative date - but maybe you have to setup one of these for each date you want to wait for.  

Something that would be nice:

HivePartitionRangeSensor(
   table=my_schema.my_table, 
   date_start='{{macros.ds_add(ds, -7)}}',
   date_end='{{ds}}'
)

Also, another option that would be nice would be waiting for jobs with a different date to finish.  So something like:
t2.set_upstream_range(t1,'{{macros.ds_add(ds, -7)}}','{{ds}}')

**Comment by artwr** [comment]
Hey Charlie,
For 2) one solution would be to create them programmatically(see below), but I agree that there is room for a new operator.

```python
day_span = 7
for i in range(day_span):
    s = HivePartitionSensor(
    task_id="wf_myschema_mytable_" + i + "_days_before",
    table="my_schema.my_table", 
    partition="ds='{{ macros.ds_add(ds, -"+ i +") }}'",
    dag=dag
    )
    t2.set_upstream(s)

```

For your second remark, if you toggle depends_on_past for your DAG, then the task for ds will only run if the task ran successfully for the previous execution date. This way, and provided you boostrapped your   jobs by running the first 7 days manually, the constraint would work going forward.

Though I will let @mistercrunch comment more if he'd like.

Best,
Arthur

**Comment by cgelman** [comment]
thanks @artwr - your programmatic solution definitely works.  

And that's a fanstastic point about setting depends_on_past being true - that could simplify things a lot for my dependency management.  but if we set depends_on_past - we can't backfill all sorts of things simultaneously.   maybe i will use depends on past= false for the backfill of earlier jobs, and then depends_on_past going forward.

Much appreciated!
Charlie

**Comment by mistercrunch** [comment]
@cgelman that sounds like the right approach for now. I wouldn't oppose a feature that would add partition ranges to HivePartitionSensor, though the two options above are good enough that it might not be super high value.
