### ISSUE TITLE
dependency on tasks in another dag

### ISSUE THREAD

**Issue by cgelman** [mistercrunch/Airflow#231]
Is it possible to depend on tasks in another DAG? 

I tried setting up 2 dags where a task in the second dag depends on the first one.  Airflow correctly shows that dag2's tasks depend on tasks in dag1, but when the tasks have been run for dag1, airflow doesn't consider those tasks as having run for dag2 and dag2's tasks wait forever.   Here's the code I used to test:

dep_test1.py:
```python
dag = DAG('dep_test1', default_args=default_args)

sleep1 = BashOperator(
    task_id='sleep1',
    depends_on_past=False,
    bash_command='sleep 5',
    dag=dag)

bash_cmd1 = BashOperator(
    task_id='bash_cmd1',
    depends_on_past=False,
    bash_command="echo 'running command #1'",
    dag=dag)

bash_cmd1.set_upstream(sleep1)
```

dep_test2.py:
```python
import dep_test1
dag2 = DAG('dep_test2', default_args=default_args)

sleep2 = BashOperator(
    task_id='sleep2',
    depends_on_past=False,
    bash_command='sleep 5',
    dag=dag2)

bash_cmd2 = BashOperator(
    task_id='bash_cmd2',
    depends_on_past=False,
    bash_command="echo 'running command #2'",
    dag=dag2)

bash_cmd2.set_upstream(sleep2)
bash_cmd2.set_upstream(dep_test1.bash_cmd1)   ## this is the key point
```

**Comment by mistercrunch** [comment]
Check out the `ExternalTaskSensor`:
http://pythonhosted.org/airflow/code.html#airflow.operators.ExternalTaskSensor

**Comment by mistercrunch** [comment]
I should probably raise an error when trying to set dependencies across dags directly (not using the ExternalTaskSensor)

**Comment by cgelman** [comment]
That's beautiful!   Exactly what I needed.

Thanks!
Charlie
