### ISSUE TITLE
Add env param to BashOperator

### ISSUE THREAD

**Issue by codewithcheese** [mistercrunch/airflow#246]
Would you be interested in the this pull?

https://github.com/mistercrunch/airflow/compare/master...codewithcheese:bash_env_param

**Comment by mistercrunch** [comment]
Totally, this is useful. I just doubled-checked that the default for env in Popen is None, so that shouldn't affect any of the current behavior.

**Comment by codewithcheese** [comment]
Cool, sent pull request.
